/*
https://www.techonthenet.com/oracle/functions/nth_value.php
https://www.techonthenet.com/oracle/functions/nth_value_ddl.php
*/
SELECT DISTINCT dept_id,
  NTH_VALUE(salary,2) OVER (PARTITION BY dept_id ORDER BY salary DESC RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "SECOND HIGHEST"
FROM employees_1
WHERE dept_id IN (10,20)
ORDER BY dept_id;
SELECT DISTINCT DEPARTMENT ,
  NTH_VALUE(SALARY,2) OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "2ND HIGHEST"
FROM STAFF
WHERE DEPARTMENT IN ('Automotive','Baby','Beauty','Books')
ORDER BY 1;
/* DEPARTMENT 4TH HIGHEST
Automotive 144724
Baby 148573
Beauty 143853
Books 146701
RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING -- THIS SAYS INCLUDE ALL ROWS PRECEDING AND FOLLOWING */
SELECT DISTINCT DEPARTMENT ,
  NTH_VALUE(SALARY,2) OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS "2ND HIGHEST"
FROM STAFF
WHERE DEPARTMENT IN ('Automotive','Baby','Beauty','Books')
ORDER BY 1;
/* WITHOUT RANGE OPERATOR THE NULLS ARE COMING AS  --always use range clause to get correct result
windowing_clause                                               Description
RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW               Last row in the window changes as the current row changes (default)
RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING               First row in the window changes as the current row changes
RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING       All rows are included in the window, regardless of the current row
*/
SELECT A.FIRSTNAME ,
  A.GENDER ,
  A.WEIGHT ,
  FIRST_VALUE(FIRSTNAME) OVER(PARTITION BY A.GENDER ORDER BY WEIGHT DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) "HEAVIEST WEIGHT" ,
  LAST_VALUE(FIRSTNAME) OVER(PARTITION BY A.GENDER ORDER BY WEIGHT DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) "LIGHT WEIGHT"
FROM CHILDSTAT A ;
SELECT A.FIRSTNAME ,
  A.GENDER ,
  A.WEIGHT ,
  SUM(WEIGHT) OVER(PARTITION BY A.GENDER ORDER BY WEIGHT  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) "WT_RUN" ,
  SUM(WEIGHT) OVER(PARTITION BY A.GENDER ORDER BY WEIGHT  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) "CURRENT_ROW_UNBOUNDED"
FROM CHILDSTAT A   ;

/*  RESULTS 

FIRSTNAME	 GENDER	  WEIGHT	WT_RUN	CURRENT_ROW_UNBOUNDED
ROSEMARY	  F   	  123	    999	      123
LAUREN	    F	      876   	999	      999
ALBERT	    M	      150	    960	      150
TOMMY	      M	      167   	960	      317
BUDDY	      M	      189	    960	      506
FARQUAR	    M      	198   	960	      704
SIMON	      M	      256	    960	      960 
*/

SELECT A.FIRSTNAME, A.GENDER, A.WEIGHT , AVG(A.WEIGHT) OVER(PARTITION BY GENDER ORDER BY WEIGHT ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AVG_3 FROM CHILDSTAT A;


SELECT A.FIRSTNAME, A.GENDER, A.WEIGHT , AVG(A.WEIGHT) OVER(PARTITION BY GENDER ORDER BY WEIGHT ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AVG_3 FROM CHILDSTAT A;
