/* NTILE divides the data into number of groups as mentioned in the argument */
SELECT NTILE(4) OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) TILE , SALARY ,ID,DEPARTMENT FROM STAFF;
SELECT COUNT(DISTINCT GENDER) OVER () ,DEPARTMENT FROM STAFF;