SELECT DEPARTMENT , SALARY, RANK() OVER(PARTITION BY  DEPARTMENT ORDER BY SALARY DESC) RANK,
ROW_NUMBER() OVER(PARTITION BY  DEPARTMENT  ORDER BY SALARY DESC) ROWNUMBER ,
PERCENT_RANK() OVER(PARTITION BY  DEPARTMENT  ORDER BY SALARY DESC) PERCTRANK
FROM STAFF;
 
SELECT * FROM STAFF A   WHERE SALARY = 78157 ;
/* Finding employees with same salary */

SELECT  DEPARTMENT , SALARY, RANK() OVER(PARTITION BY  DEPARTMENT ORDER BY SALARY DESC) RANK,
ROW_NUMBER() OVER(PARTITION BY  DEPARTMENT  ORDER BY SALARY DESC) RNK  FROM STAFF WHERE SALARY IN (SELECT SALARY FROM STAFF GROUP BY SALARY HAVING COUNT(*) > 1);

/* FINDING PERCENTILE RANK OF SALARY OVER REGION - IT WILL FIND THE PERCENTAGE OF SALARY OVER TOTAL */

SELECT SUM(SALARY) ,REGION_ID, RANK() OVER (PARTITION BY REGION_ID ORDER BY SUM(SALARY) DESC) RNK,
PERCENT_RANK() OVER (PARTITION BY REGION_ID ORDER BY SUM(SALARY) DESC) PERCNT_RANK
FROM STAFF GROUP BY REGION_ID ,REGION_ID;
