SELECT RATIO_TO_REPORT(SALARY) OVER (PARTITION BY DEPARTMENT) RATIO,SALARY,DEPARTMENT FROM STAFF ;
/* THIS FUNCTION GIVES RATIO TO THAT OF TOTAL ..IN THIS CASE IT IS THE RATIO TO THAT OF TOTAL FOR EACH DEPARTMENT */

SELECT DEPARTMENT ,GENDER ,SUM(SALARY),CASE WHEN GROUPING(GENDER) IN (1) THEN 'Total Gender' ELSE GENDER END GEN FROM STAFF GROUP BY ROLLUP(DEPARTMENT,GENDER);

SELECT * FROM STAFF;